### PR TITLE
Optional themed regular trainers

### PR DESCRIPTION
**Pull request by Metatayte**
Adds a checkbox to Foe Randomizer. A sub-option to Type Theming. This essentially lets users decide if they want non-gym trainers to have type themes or not.

### CODE REVIEW

**Comment by tom-overton** [comment]
I've spoken to Ajarmar about this and there are two things about the UI that we'd like changed:
- This new setting exists as a checkbox, but the checkbox section of the trainer UI is really crowded. Can this be a radio button? Granted, that section is also a little crowded too, but it's better than another checkbox.
- Right now, the current behavior of "Type Themed Trainers" is changed; the checkbox brings back the behavior that users have been using for years. The current setting needs to keep the current behavior so as not to confuse users.

Given the above two points, I think there should be two radio buttons for Type Themed Trainers: one radio button that's something like "Type Themed Trainers (all)" for the current setting and a second radio button that's something like "Type Themed Trainers (type specialists)" for your new behavior. These names are just totally off-the-cuff, so if you can think of anything better please use it.

**Comment by Metatayte** [comment]
I went ahead and made some radio buttons between the General foe button group and the checkboxes. Looking at the UI, if we're really set on keeping the window as small as possible, there still seems to be some space below. We could potentially make check boxes similar to those for foe items. Then users could select 'Boss' / 'Important' / 'Regular' type theming. In any case, this commit is just to show what it would look like. I'm still working out how to have 'All' pokemon type themed by default. Radio buttons make it slightly more difficult than a checkbox

**Comment by tom-overton** [comment]
Apologies for the long delay on responding to this. There are two things that need changing:
1. When I said "make it a radio button", I meant [these radio buttons](https://user-images.githubusercontent.com/12245827/134716660-a2cad56f-7956-4f45-a41b-47163976dbb8.png), not a separate set of radio buttons.
2. You need to make sure to save the new settings in Settings.java's `toString` and then restore it in `fromString`. Without it, premade seeds are completely broken. If you need help understanding how to do this, I did it recently in [this commit](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/commit/9ce5dd1fa37015a0e3c0d7c3ae77f5600ba7e81c). Make sure you are up-to-date with the latest `master` and then add it to the `TrainersMod` enum. If you want, we can handle doing this, so just let us know.

**Comment by Ajarmar** [comment]
Closing due to inactivity.

**Pull request closed without merging**
